{
 "title": "FastAPI Дашборд - Тестовое redsoft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Запросов в минуту",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Количество ошибок (30 сек)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{status=\"500\"}[10s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"web\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (handler)(\n  rate(http_request_duration_seconds_sum{job=\"web\",handler!~\"/metrics\"}[1m])\n)\n/\nsum by (handler)(\n  rate(http_request_duration_seconds_count{job=\"web\",handler!~\"/metrics\"}[1m])\n)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Запросы < 100 ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[10s]) \n/ ignoring (le) increase(http_request_duration_seconds_count[10s])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"web\"}[6s]) * 100",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}